# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  - ps: New-Item ~/.R/gargle -ItemType Directory
  - ps: |
      if (-not $env:APPVEYOR_PULL_REQUEST_NUMBER)
      {
        nuget install secure-file -ExcludeVersion
        C:\projects\googledrive\secure-file\tools\secure-file.exe -decrypt C:\projects\googledrive\tests\testthat\test-tokens\av_googledrive-testing.json.enc -secret $env:my_secret -out  C:\Users\appveyor\.R\gargle\googledrive-testing.json
      }
  - ps: Test-Path ~/.R/gargle/googledrive-testing.json -PathType Leaf
  - ps: Bootstrap

# Adapt as necessary starting from here

environment:
  global:
    USE_RTOOLS: true
    WARNINGS_ARE_ERRORS: 1
  my_secret:
    secure: nVYnVjtzpqZ2V87uoBzyDQ==

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
