on:
  push:
    branches: master
  schedule:
    # * is a special character in YAML so we have to quote this string
    # 12 (UTC) - 7 or 8 (offset for Pacific) = 4am or 5am = I'm asleep
    # also try to avoid overlap with same job for googlesheets4 because quota
    # https://crontab.guru is your friend
    - cron:  '30 12 * * *'

name: pkgdown

jobs:
  pkgdown:
    runs-on: macOS-latest
    if: "github.event_name == 'schedule' || contains(github.event.head_commit.message, '[pkgdown]')"

    env:
      GOOGLEDRIVE_PASSWORD: ${{ secrets.GOOGLEDRIVE_PASSWORD }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master

      - name: Query dependencies
        run: |
          # getting dev remotes for better behaviour re: installation order
          install.packages("https://github.com/r-lib/remotes/archive/master.tar.gz", repos = NULL)
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: macOS-r-4.0-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: macOS-r-4.0-1-

      - name: Install dependencies
        run: |
          # temporary hack until there's a macOS binary for ps
          install.packages("ps", type = "source")
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("tidyverse")
          remotes::install_github("tidyverse/tidytemplate")
          remotes::install_dev("pkgdown")
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Deploy package
        run: pkgdown::deploy_to_branch(new_process = FALSE)
        shell: Rscript {0}
